### ISSUE TITLE
It does not work on android device

### ISSUE THREAD

**Issue by ghost** [hi5dev/box2d_pexml#1]
In the desktop version runs fine, but when running on the Android device, there is an error in the string:

   physicsBodies = new PEXML (Gdx.files.internal ( "physics.xml") file ().);

How to solve a problem ?

**Comment by travishaynes** [comment]
Please post the error that you're seeing, as well as the code that is producing it. The line of code you provided does have an error, which can be fixed like this:

``` java
PEXML pexml = new PEXML(Gdx.files.internal("physics.xml").file());
```

You can then get the physics bodies using the PEXML instance. Just creating the instance doesn't provide you with a physics body.

If you want more help, please post the actual error that you're getting, instead of just saying that you are seeing one, as well as the code that's producing the error. I need to be able to reproduce it on my end to help you.

**Comment by RodneyEllis** [comment]
I'm using Android Studio and LibGDX.  It works really well when generating a desktop application but when I try an Android simulation it seems to call on JAXBContext and fail.  From my brief research it looks like Android will not allow JAXB and has its own version of XML parsers.  The error is:
stack=java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/JAXBContext;

**Comment by snask** [comment]
I am also experiencing this issue. Have I missed something or is a workaround in development?

**Comment by JeremiahReichardt** [comment]
I too have this issue
`java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/JAXBContext;
at com.hi5dev.box2d_pexml.PEXML.loadXML(PEXML.java:124)
at com.hi5dev.box2d_pexml.PEXML.<init>(PEXML.java:24)
`
From calling 
`physicsBodies = new PEXML(Gdx.files.internal("physics.xml").file());`

This works on desktop which is great but fails for Android builds.

**Comment by kharak** [comment]
me too have this issue, can anybody help or this library does not work for android?
error
ava.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/JAXBContext;  at com.hi5dev.box2d_pexml.PEXML.loadXML(PEXML.java:124) at com.hi5dev.box2d_pexml.PEXML.<init>(PEXML.java:24)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.bind.JAXBContext" on path: DexPathList[[dex file "/data/data/com.myplayer.football/files/instant-run/dex/slice-slice_9...

**Comment by kharak** [comment]
me too have this issue, can anybody help or this library does not work for android?
error
ava.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/JAXBContext;  at com.hi5dev.box2d_pexml.PEXML.loadXML(PEXML.java:124) at com.hi5dev.box2d_pexml.PEXML.<init>(PEXML.java:24)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.bind.JAXBContext" on path: DexPathList[[dex file "/data/data/com.myplayer.football/files/instant-run/dex/slice-slice_9...

**Comment by kharak** [comment]
me too have this issue, can anybody help or this library does not work for android?
error
ava.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/JAXBContext;  at com.hi5dev.box2d_pexml.PEXML.loadXML(PEXML.java:124) at com.hi5dev.box2d_pexml.PEXML.<init>(PEXML.java:24)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.bind.JAXBContext" on path: DexPathList[[dex file "/data/data/com.myplayer.football/files/instant-run/dex/slice-slice_9...

**Comment by kharak** [comment]
me too have this issue, can anybody help or this library does not work for android?
error
ava.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/bind/JAXBContext;  at com.hi5dev.box2d_pexml.PEXML.loadXML(PEXML.java:124) at com.hi5dev.box2d_pexml.PEXML.<init>(PEXML.java:24)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.xml.bind.JAXBContext" on path: DexPathList[[dex file "/data/data/com.myplayer.football/files/instant-run/dex/slice-slice_9...

**Comment by ghost** [comment]
same

**Comment by kharak** [comment]
Is there any other physics editor available,which works well with Android device?

**Comment by ghost** [comment]
There's this one: http://www.aurelienribon.com/blog/projects/physics-body-editor/
and it uses json instead of xml.

I haven't used it though

**Comment by kharak** [comment]
I tried already, but don't know how to load into libgdx,loader a Java file provided wasn't running

**Comment by JeremiahReichardt** [comment]
Overlap2D has a built in physics editor and works on Android devices.

**Comment by travishaynes** [comment]
I haven't had time to work on this in a while because game dev is just a hobby for me and I've been really busy with work. Pull requests are more than welcome if you want to find the solution. It should be pretty simple. All you have to do is switch it over to a different XML library to get it to work on Android, or just find a way to include JAXB in your project.

There's a solution to getting JAXB working posted in this stackoverflow thread that you can try out:

http://stackoverflow.com/questions/5461127/using-jaxb-with-google-android

**Comment by ghost** [comment]
@kharak have you found a solution?

I found a patch to the parsing issue on the physics body editor I linked: https://gist.github.com/zudov/5566204

I haven't tried it yet though, but by looking at it I can see that the classes that were causing errors have been changed.

**Comment by kharak** [comment]
i tried adding this class to my project and it works with physics body editor
https://gist.github.com/grulg/8691e7ee7709367ce165
but remember initialize world before initializing Loader.

**Comment by progfiles** [comment]
It is no longer time update. And it is not work in Android. How I can return money for license?

**Comment by Yanhenning** [comment]
Someone founds a solution for this error? Instead of change the physics editor
